### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by boswald314** [thopit/Creatures#1]
[log.txt](https://github.com/thopit/Creatures/files/139364/log.txt)

So I've attached the result of running gradlew build. I'm not super familiar with Java, and not at all with Gradle, but many of these seem to be simple errors. It feels like something that would happen when using the wrong version, but from my understanding grade takes care of this?

**Comment by thopit** [comment]
Yes, the build errors are because of an outdated Java version on your system. You need to install the newest JDK (1.8) and point your JAVA_HOME environment variable to the bin directory of the JDK (e.g C:\Program Files\Java\jdk1.8.0_45\bin)

**Comment by boswald314** [comment]
Thanks very much. I figured it was something stupid like that. I couldn't figure out what version it was supposed to be, and figured I wasn't going to get anywhere in an environment where I only half understand half of what's going on.

**Comment by thopit** [comment]
To be honest, I didn't explicitly mention the needed Java version for my program.
If you're still interested, you are very welcome to ask me any question here or via mail.
